title: "Thalia AI"
description: "AI-Powered Menopause Support Platform - Empowering women with evidence-based care"
baseurl: ""
url: "https://你的用户名.github.io/仓库名"  # 请替换为你的实际地址

# 主题和样式
theme: minima

# 网站信息
author:
  name: "Thalia AI Team"
  email: "contact@thalia-ai.com"

# 导航菜单
header_pages:
  - index.md
  - about.md

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown 处理
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 网站设置
show_excerpts: true
excerpt_separator: "<!--more-->"

# 自定义变量
minima:
  skin: auto  # 自动适应深色/浅色模式
  social_links:
    - { platform: github, user_url: "https://github.com/你的用户名/仓库名" }
  # 自定义头部
  header_pages:
    - index.md
    - about.md

# Google Analytics（可选）
# google_analytics: UA-XXXXXXXX-X

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md
  - LICENSE
  - "*.gemspec"

# 包含文件
include:
  - _pages

# 集合配置
collections:
  pages:
    output: true
    permalink: /:name/

# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Thalia AI Team"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# 压缩设置
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false